# Generated by Django 2.2.4 on 2021-12-20 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='l_desk',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
